import Link from "next/link";
import Image from "next/image";
import PrintButton from "./PrintButton";
import { CrownMark } from "./Logo";
const chapters = ["전체 사용 흐름 한눈에 보기", "선생님 계정 만들기", "반 만들기와 학생 등록", "Student Card 명단 확인과 반 매칭", "과제(지문) 등록하기", "학생 제출 확인하기", "성적 추이와 CSV 내려받기", "점수 읽는 법", "배지와 쿠폰", "월말 리포트 만들기", "학기가 끝난 반 정리하기", "공지사항 보내기", "반 이동과 인수인계", "학부모 열람 링크", "Slack 알림", "자주 묻는 질문"];
const ids = ["흐름", "1", "2", "2-1", "3", "4", "4-1", "5", "6", "7", "8", "9", "🔀", "10", "11", "12"];
export function ManualShell({title, subtitle, children}: {title:string;subtitle:string;otherHref?:string;otherLabel?:string;children:React.ReactNode}) {
 return <div className="min-h-screen bg-[#f3f6fb] text-slate-800 print:bg-white">
 <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-6 py-5"><Link href="/" className="flex items-center gap-3 font-bold text-brand"><CrownMark className="h-9 w-9"/>유스피킹 <span className="text-sm font-normal text-slate-400">사용 가이드</span></Link><div className="no-print flex gap-3 text-sm"><Link href="/manual/student" className="rounded-full border px-4 py-2">학생용 가이드</Link><PrintButton className="rounded-full bg-brand px-4 py-2 font-medium text-white"/></div></div></header>
 <div className="mx-auto max-w-7xl px-5 py-10 md:px-8 md:py-14 print:p-0"><div className="mb-10 rounded-[28px] bg-[#173967] p-7 text-white md:p-12 print:bg-white print:text-black"><p className="mb-4 text-xs font-semibold tracking-[0.18em] text-blue-200 print:text-slate-500">YUSPEAKING · TEACHER GUIDE</p><h1 className="text-3xl font-bold tracking-tight md:text-4xl">{title}</h1><p className="mt-4 max-w-2xl leading-7 text-blue-100 print:text-slate-600">{subtitle}</p><div className="mt-7 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-white/10 px-3 py-2">실제 화면으로 따라하기</span><span className="rounded-full bg-white/10 px-3 py-2">2026.10 업데이트</span></div></div>
 <div className="grid items-start gap-10 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="no-print lg:sticky lg:top-6"><p className="mb-3 text-xs font-bold tracking-widest text-slate-400">CONTENTS</p><nav aria-label="가이드 목차" className="grid grid-cols-2 gap-1 lg:grid-cols-1">{chapters.map((t,i)=><a key={ids[i]} href={"#chapter-"+ids[i]} className="rounded-lg px-3 py-2 text-sm text-slate-600 transition hover:bg-white hover:text-brand"><span className="mr-2 text-xs text-slate-400">{String(i+1).padStart(2,"0")}</span>{t}</a>)}</nav></aside><article className="min-w-0"><div className="mb-5 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-900">화면은 실제 유스피킹 프로그램에서 캡처했습니다. 학생·반·점수는 설명을 위한 예시 데이터입니다. 이미지를 누르면 크게 볼 수 있습니다.</div>{children}<footer className="mt-10 border-t py-6 text-xs text-slate-400">목동유쌤영어 · YuSpeaKing 선생님 가이드</footer></article></div></div></div>;
}
export function Section({no,title,children}: {no:number|string;title:string;children:React.ReactNode}) {return <section id={"chapter-"+no} className="mb-6 scroll-mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-8 print:border-0 print:p-0 print:shadow-none"><h2 className="mb-6 flex items-center gap-3 text-xl font-bold tracking-tight"><span className="flex h-9 min-w-9 items-center justify-center rounded-xl bg-blue-50 px-2 text-sm text-brand">{no}</span>{title}</h2><div className="space-y-5 text-sm leading-7 text-slate-600">{children}</div></section>}
export function GuideScreen({name,title,caption}: {name:string;title:string;caption:string}) {const src="/manual/teacher/"+name+".png";return <figure className="my-6 overflow-hidden rounded-xl border border-slate-200 bg-slate-50 print-avoid-break"><div className="flex items-center gap-2 border-b px-4 py-3 text-xs font-semibold text-slate-500"><span className="h-2 w-2 rounded-full bg-blue-400"/>{title}<span className="ml-auto font-normal">예시 화면</span></div><a href={src} target="_blank" rel="noreferrer" aria-label={title+" 크게 보기 (새 탭)"}><Image src={src} alt={caption} width={1440} height={1000} className="h-auto w-full" unoptimized/></a><figcaption className="border-t bg-white px-4 py-3 text-xs leading-6 text-slate-500">{caption}</figcaption></figure>}
